server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: service-order
  datasource:
    url: jdbc:mysql://150.158.141.30:3306/Hospital?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: "@liuJIAN0523"
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
#  mapper-locations: classpath:edu/swu/cs/mapper/xml/*.xml

