package swu.lj.ssm.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbggenerated Wed Mar 02 20:58:56 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.User_name
     *
     * @mbggenerated Wed Mar 02 20:58:56 CST 2022
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.User_password
     *
     * @mbggenerated Wed Mar 02 20:58:56 CST 2022
     */
    private String userPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Wed Mar 02 20:58:56 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Wed Mar 02 20:58:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.User_name
     *
     * @return the value of admin.User_name
     *
     * @mbggenerated Wed Mar 02 20:58:56 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.User_name
     *
     * @param userName the value for admin.User_name
     *
     * @mbggenerated Wed Mar 02 20:58:56 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.User_password
     *
     * @return the value of admin.User_password
     *
     * @mbggenerated Wed Mar 02 20:58:56 CST 2022
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.User_password
     *
     * @param userPassword the value for admin.User_password
     *
     * @mbggenerated Wed Mar 02 20:58:56 CST 2022
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }
}