server:
  port:8080

spring:
  datasource:
    name: redisCache
    url: jdbc:mysql://150.158.141.30:3306/redisCache?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: "@liuJIAN0523"
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    servlet:
      context-path=/test
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        min-idle: 0
#        max-idle: 8
#        max-wait: -1
#      # ??????????
#    timeout: 5000
#  cache:
#    type: redis
mybatis:
  mapper-locations=classpath:com/example/rediscache/mapper/*:
    xml:
  configuration:
    local-cache-scope: statement #一级缓存指定为statement级别
    cache-enabled: true
logging:
  level:
    com:
      example:
        rediscache:
          mapper: debug

