#spring:
#  security:
#    user:
#      name: liujian
#      password: liujian
spring:
  datasource:
      url: jdbc:mysql://150.158.141.30:3306/springSecurity?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: "@liuJIAN0523"
      driver-class-name: com.mysql.cj.jdbc.Driver