package com.example.rediscache.polo;

import java.io.Serializable;

public class User implements Serializable {
    private static final long serialVersionUID =-1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.t_id
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.t_name
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    private String tName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.t_age
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    private Integer tAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.t_address
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    private String tAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.t_password
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    private Integer tPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.t_id
     *
     * @return the value of t_user.t_id
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.t_id
     *
     * @param tId the value for t_user.t_id
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.t_name
     *
     * @return the value of t_user.t_name
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.t_name
     *
     * @param tName the value for t_user.t_name
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.t_age
     *
     * @return the value of t_user.t_age
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    public Integer gettAge() {
        return tAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.t_age
     *
     * @param tAge the value for t_user.t_age
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    public void settAge(Integer tAge) {
        this.tAge = tAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.t_address
     *
     * @return the value of t_user.t_address
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    public String gettAddress() {
        return tAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.t_address
     *
     * @param tAddress the value for t_user.t_address
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    public void settAddress(String tAddress) {
        this.tAddress = tAddress == null ? null : tAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.t_password
     *
     * @return the value of t_user.t_password
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    public Integer gettPassword() {
        return tPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.t_password
     *
     * @param tPassword the value for t_user.t_password
     *
     * @mbggenerated Thu Apr 14 18:18:47 CST 2022
     */
    public void settPassword(Integer tPassword) {
        this.tPassword = tPassword;
    }
}