server:
  port: 8088
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: service-hotOrder
  datasource:
    url: jdbc:mysql://150.158.141.30:3306/Hospital?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: "@liuJIAN0523"
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    #虚拟主机地址
    virtual-host: /
    #连接超时时间
    connection-timeout: 15000
    publisher-returns: true
    template:
      mandatory: true
    publisher-confirm-type: correlated
    listener:
      #设置监听容器（Listener container）类型，如不设置，将会默认为SimpleRabbitListenerContainerFactory，且下面的direct配置不生效
#      type: direct
#      direct:
#        #设置监听为手动答应模式
#        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
#  mapper-locations: classpath:edu/swu/cs/mapper/xml/*.xml

